// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbaxvfyozlsqlrvnrdtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiYXh2ZnlvemxzcWxydm5yZHRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NDI0MjcsImV4cCI6MjA2MTMxODQyN30.1W4S2nNYx85MQfYpqDw5uySFyKr6oIOqKjKuyBSXiBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);